/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as BloodRequestsRouteImport } from './routes/blood-requests'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as DijkstraRouteImport } from './routes/dijkstra'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MapRouteImport } from './routes/map'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RecordsRouteImport } from './routes/records'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SosRouteImport } from './routes/sos'
import { Route as SosHistoryRouteImport } from './routes/sos-history'
import { Route as TriageRouteImport } from './routes/triage'
import { Route as TriageHistoryRouteImport } from './routes/triage-history'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as DashboardAmbulanceRouteImport } from './routes/dashboard.ambulance'
import { Route as DashboardBloodBankRouteImport } from './routes/dashboard.blood-bank'
import { Route as DashboardHospitalRouteImport } from './routes/dashboard.hospital'
import { Route as DashboardPatientRouteImport } from './routes/dashboard.patient'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const BloodRequestsRoute = BloodRequestsRouteImport.update({
  id: '/blood-requests',
  path: '/blood-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const DijkstraRoute = DijkstraRouteImport.update({
  id: '/dijkstra',
  path: '/dijkstra',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsRoute = RecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SosRoute = SosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => rootRouteImport,
} as any)
const SosHistoryRoute = SosHistoryRouteImport.update({
  id: '/sos-history',
  path: '/sos-history',
  getParentRoute: () => rootRouteImport,
} as any)
const TriageRoute = TriageRouteImport.update({
  id: '/triage',
  path: '/triage',
  getParentRoute: () => rootRouteImport,
} as any)
const TriageHistoryRoute = TriageHistoryRouteImport.update({
  id: '/triage-history',
  path: '/triage-history',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/dashboard/admin',
  path: '/dashboard/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAmbulanceRoute = DashboardAmbulanceRouteImport.update({
  id: '/dashboard/ambulance',
  path: '/dashboard/ambulance',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBloodBankRoute = DashboardBloodBankRouteImport.update({
  id: '/dashboard/blood-bank',
  path: '/dashboard/blood-bank',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardHospitalRoute = DashboardHospitalRouteImport.update({
  id: '/dashboard/hospital',
  path: '/dashboard/hospital',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPatientRoute = DashboardPatientRouteImport.update({
  id: '/dashboard/patient',
  path: '/dashboard/patient',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appointments': typeof AppointmentsRoute
  '/blood-requests': typeof BloodRequestsRoute
  '/contact': typeof ContactRoute
  '/contacts': typeof ContactsRoute
  '/dijkstra': typeof DijkstraRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/records': typeof RecordsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sos': typeof SosRoute
  '/sos-history': typeof SosHistoryRoute
  '/triage': typeof TriageRoute
  '/triage-history': typeof TriageHistoryRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/ambulance': typeof DashboardAmbulanceRoute
  '/dashboard/blood-bank': typeof DashboardBloodBankRoute
  '/dashboard/hospital': typeof DashboardHospitalRoute
  '/dashboard/patient': typeof DashboardPatientRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appointments': typeof AppointmentsRoute
  '/blood-requests': typeof BloodRequestsRoute
  '/contact': typeof ContactRoute
  '/contacts': typeof ContactsRoute
  '/dijkstra': typeof DijkstraRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/records': typeof RecordsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sos': typeof SosRoute
  '/sos-history': typeof SosHistoryRoute
  '/triage': typeof TriageRoute
  '/triage-history': typeof TriageHistoryRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/ambulance': typeof DashboardAmbulanceRoute
  '/dashboard/blood-bank': typeof DashboardBloodBankRoute
  '/dashboard/hospital': typeof DashboardHospitalRoute
  '/dashboard/patient': typeof DashboardPatientRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appointments': typeof AppointmentsRoute
  '/blood-requests': typeof BloodRequestsRoute
  '/contact': typeof ContactRoute
  '/contacts': typeof ContactsRoute
  '/dijkstra': typeof DijkstraRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/records': typeof RecordsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sos': typeof SosRoute
  '/sos-history': typeof SosHistoryRoute
  '/triage': typeof TriageRoute
  '/triage-history': typeof TriageHistoryRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/ambulance': typeof DashboardAmbulanceRoute
  '/dashboard/blood-bank': typeof DashboardBloodBankRoute
  '/dashboard/hospital': typeof DashboardHospitalRoute
  '/dashboard/patient': typeof DashboardPatientRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/appointments'
    | '/blood-requests'
    | '/contact'
    | '/contacts'
    | '/dijkstra'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/map'
    | '/profile'
    | '/records'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/sos'
    | '/sos-history'
    | '/triage'
    | '/triage-history'
    | '/verify-otp'
    | '/dashboard/admin'
    | '/dashboard/ambulance'
    | '/dashboard/blood-bank'
    | '/dashboard/hospital'
    | '/dashboard/patient'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/appointments'
    | '/blood-requests'
    | '/contact'
    | '/contacts'
    | '/dijkstra'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/map'
    | '/profile'
    | '/records'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/sos'
    | '/sos-history'
    | '/triage'
    | '/triage-history'
    | '/verify-otp'
    | '/dashboard/admin'
    | '/dashboard/ambulance'
    | '/dashboard/blood-bank'
    | '/dashboard/hospital'
    | '/dashboard/patient'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/appointments'
    | '/blood-requests'
    | '/contact'
    | '/contacts'
    | '/dijkstra'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/map'
    | '/profile'
    | '/records'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/sos'
    | '/sos-history'
    | '/triage'
    | '/triage-history'
    | '/verify-otp'
    | '/dashboard/admin'
    | '/dashboard/ambulance'
    | '/dashboard/blood-bank'
    | '/dashboard/hospital'
    | '/dashboard/patient'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppointmentsRoute: typeof AppointmentsRoute
  BloodRequestsRoute: typeof BloodRequestsRoute
  ContactRoute: typeof ContactRoute
  ContactsRoute: typeof ContactsRoute
  DijkstraRoute: typeof DijkstraRoute
  FeaturesRoute: typeof FeaturesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  ProfileRoute: typeof ProfileRoute
  RecordsRoute: typeof RecordsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SosRoute: typeof SosRoute
  SosHistoryRoute: typeof SosHistoryRoute
  TriageRoute: typeof TriageRoute
  TriageHistoryRoute: typeof TriageHistoryRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardAmbulanceRoute: typeof DashboardAmbulanceRoute
  DashboardBloodBankRoute: typeof DashboardBloodBankRoute
  DashboardHospitalRoute: typeof DashboardHospitalRoute
  DashboardPatientRoute: typeof DashboardPatientRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blood-requests': {
      id: '/blood-requests'
      path: '/blood-requests'
      fullPath: '/blood-requests'
      preLoaderRoute: typeof BloodRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dijkstra': {
      id: '/dijkstra'
      path: '/dijkstra'
      fullPath: '/dijkstra'
      preLoaderRoute: typeof DijkstraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records': {
      id: '/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof RecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sos': {
      id: '/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof SosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sos-history': {
      id: '/sos-history'
      path: '/sos-history'
      fullPath: '/sos-history'
      preLoaderRoute: typeof SosHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/triage': {
      id: '/triage'
      path: '/triage'
      fullPath: '/triage'
      preLoaderRoute: typeof TriageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/triage-history': {
      id: '/triage-history'
      path: '/triage-history'
      fullPath: '/triage-history'
      preLoaderRoute: typeof TriageHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/ambulance': {
      id: '/dashboard/ambulance'
      path: '/dashboard/ambulance'
      fullPath: '/dashboard/ambulance'
      preLoaderRoute: typeof DashboardAmbulanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/blood-bank': {
      id: '/dashboard/blood-bank'
      path: '/dashboard/blood-bank'
      fullPath: '/dashboard/blood-bank'
      preLoaderRoute: typeof DashboardBloodBankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/hospital': {
      id: '/dashboard/hospital'
      path: '/dashboard/hospital'
      fullPath: '/dashboard/hospital'
      preLoaderRoute: typeof DashboardHospitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/patient': {
      id: '/dashboard/patient'
      path: '/dashboard/patient'
      fullPath: '/dashboard/patient'
      preLoaderRoute: typeof DashboardPatientRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppointmentsRoute: AppointmentsRoute,
  BloodRequestsRoute: BloodRequestsRoute,
  ContactRoute: ContactRoute,
  ContactsRoute: ContactsRoute,
  DijkstraRoute: DijkstraRoute,
  FeaturesRoute: FeaturesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  ProfileRoute: ProfileRoute,
  RecordsRoute: RecordsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SosRoute: SosRoute,
  SosHistoryRoute: SosHistoryRoute,
  TriageRoute: TriageRoute,
  TriageHistoryRoute: TriageHistoryRoute,
  VerifyOtpRoute: VerifyOtpRoute,
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardAmbulanceRoute: DashboardAmbulanceRoute,
  DashboardBloodBankRoute: DashboardBloodBankRoute,
  DashboardHospitalRoute: DashboardHospitalRoute,
  DashboardPatientRoute: DashboardPatientRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
