import { jsPDF } from "jspdf";
import { format } from "date-fns";

export type TriageReportRow = {
  id: string;
  severity: "critical" | "high" | "moderate" | "low";
  risk_score: number;
  confidence: number;
  department: string;
  hospital_recommendation: string | null;
  possible_conditions: string[] | null;
  ai_summary: string | null;
  symptoms: string[] | null;
  vitals: Record<string, unknown> | null;
  created_at: string;
};

export function downloadTriagePdf(r: TriageReportRow, patientName?: string) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const w = doc.internal.pageSize.getWidth();
  let y = 56;

  doc.setFillColor(37, 99, 235);
  doc.rect(0, 0, w, 40, "F");
  doc.setTextColor(255).setFontSize(16).setFont("helvetica", "bold");
  doc.text("MediRoute — AI Triage Report", 40, 26);

  doc.setTextColor(20).setFont("helvetica", "normal").setFontSize(10);
  doc.text(`Patient: ${patientName ?? "—"}`, 40, y); y += 14;
  doc.text(`Report ID: ${r.id}`, 40, y); y += 14;
  doc.text(`Generated: ${format(new Date(r.created_at), "PPpp")}`, 40, y); y += 22;

  doc.setFont("helvetica", "bold").setFontSize(12).text("Assessment", 40, y); y += 16;
  doc.setFont("helvetica", "normal").setFontSize(11);
  doc.text(`Severity: ${r.severity.toUpperCase()}`, 40, y); y += 14;
  doc.text(`Risk score: ${r.risk_score}/100`, 40, y); y += 14;
  doc.text(`Confidence: ${r.confidence}%`, 40, y); y += 14;
  doc.text(`Recommended dept.: ${r.department}`, 40, y); y += 14;
  if (r.hospital_recommendation) { doc.text(`Hospital: ${r.hospital_recommendation}`, 40, y); y += 14; }

  y += 6;
  doc.setFont("helvetica", "bold").text("Clinical summary", 40, y); y += 14;
  doc.setFont("helvetica", "normal");
  const summary = doc.splitTextToSize(r.ai_summary ?? "—", w - 80);
  doc.text(summary, 40, y); y += summary.length * 13 + 6;

  if (r.symptoms?.length) {
    doc.setFont("helvetica", "bold").text("Reported symptoms", 40, y); y += 14;
    doc.setFont("helvetica", "normal");
    const s = doc.splitTextToSize(r.symptoms.join(", "), w - 80);
    doc.text(s, 40, y); y += s.length * 13 + 6;
  }
  if (r.possible_conditions?.length) {
    doc.setFont("helvetica", "bold").text("Possible conditions", 40, y); y += 14;
    doc.setFont("helvetica", "normal");
    const s = doc.splitTextToSize(r.possible_conditions.join(", "), w - 80);
    doc.text(s, 40, y); y += s.length * 13 + 6;
  }
  if (r.vitals) {
    doc.setFont("helvetica", "bold").text("Vitals", 40, y); y += 14;
    doc.setFont("helvetica", "normal");
    Object.entries(r.vitals).forEach(([k, v]) => { doc.text(`${k}: ${String(v)}`, 40, y); y += 12; });
  }

  y = doc.internal.pageSize.getHeight() - 40;
  doc.setFontSize(9).setTextColor(120);
  doc.text("Generated by MediRoute AI Triage — not a substitute for professional medical advice.", 40, y);

  doc.save(`triage-${r.id.slice(0,8)}.pdf`);
}
